### ISSUE TITLE
Missing documentation and example for cache behavior parameters

### ISSUE THREAD

**Issue by catrielg** [terraform-aws-modules/terraform-aws-cloudfront#141]
## Description
In the module itself, you support the use of trusted_key_groups, trusted_signers, smooth_streaming and more for ordered and default cache behaviors. However the usage is missing from your "complete" example as well as the documentation .

**Comment by anantadurgaprasad** [comment]
I have submitted a [PR](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/143) for the same. The example uses use_forwaded_values and legacy settings

**Comment by antonbabenko** [comment]
A complete example shows many arguments, but it would be nearly impossible to maintain and very hard to understand if there were all of them and supplementary resources. That is why we show the most common ones.

Adding a smaller subset of features into a separate example (like in #143) does not make it easier because there is no way to identify which feature to include.

Let's stick to the current `complete` example and maybe extend arguments if they are very important and used often. `smooth_streaming` - is not important, but `trusted_key_groups` and `trusted_signers`are good to have in the `examples/complete` with all required supplementary resources (such as `aws_cloudfront_key_group`, `aws_cloudfront_public_key`).
